<?php
// ============================================================
// modules/backup/backup.php
// ============================================================
requireRole(ROLE_ADMIN);

$action = $_POST['action'] ?? $_GET['action'] ?? '';

// ── Topology sort: parents before children ───────────────────
function sortTablesByDependency(array $tables): array {
    // Build FK dependency map from information_schema
    $deps = array_fill_keys($tables, []);
    $fkRows = dbFetchAll(
        "SELECT TABLE_NAME, REFERENCED_TABLE_NAME
         FROM information_schema.KEY_COLUMN_USAGE
         WHERE TABLE_SCHEMA = DATABASE()
           AND REFERENCED_TABLE_NAME IS NOT NULL"
    );
    foreach ($fkRows as $r) {
        $t = $r['TABLE_NAME'];
        $ref = $r['REFERENCED_TABLE_NAME'];
        if (isset($deps[$t]) && $ref !== $t) {
            $deps[$t][] = $ref;
        }
    }

    $sorted  = [];
    $visited = [];

    function topoVisit(string $table, array &$deps, array &$visited, array &$sorted): void {
        if (isset($visited[$table])) return;
        $visited[$table] = true;
        foreach ($deps[$table] ?? [] as $dep) {
            topoVisit($dep, $deps, $visited, $sorted);
        }
        $sorted[] = $table;
    }

    foreach ($tables as $t) {
        topoVisit($t, $deps, $visited, $sorted);
    }
    return $sorted;
}

// ── Pure-PHP SQL dump ────────────────────────────────────────
function generateSqlDump(): string {
    $out   = [];
    $out[] = '-- ============================================================';
    $out[] = '-- SQL Backup generated by ' . APP_NAME;
    $out[] = '-- Date    : ' . date('Y-m-d H:i:s');
    $out[] = '-- ============================================================';
    $out[] = '';
    $out[] = 'SET FOREIGN_KEY_CHECKS=0;';
    $out[] = 'SET SQL_MODE="NO_AUTO_VALUE_ON_ZERO";';
    $out[] = 'SET time_zone="+00:00";';
    $out[] = '';

    // Get all tables then sort parents-first
    $rawTables = array_map(fn($r) => reset($r), dbFetchAll('SHOW TABLES'));
    $tables    = sortTablesByDependency($rawTables);

    // DROP in reverse order (children first) to avoid FK conflicts
    foreach (array_reverse($tables) as $table) {
        $out[] = "DROP TABLE IF EXISTS `$table`;";
    }
    $out[] = '';

    foreach ($tables as $table) {
        $createRow = dbFetch("SHOW CREATE TABLE `$table`");
        $createSql = $createRow['Create Table'] ?? '';

        $out[] = "-- --------------------------------------------------------";
        $out[] = "-- Table: `$table`";
        $out[] = "-- --------------------------------------------------------";
        $out[] = $createSql . ';';
        $out[] = '';

        $countRow = dbFetch("SELECT COUNT(*) AS cnt FROM `$table`");
        if ((int)($countRow['cnt'] ?? 0) === 0) continue;

        $chunkSize = 500;
        $offset    = 0;
        while (true) {
            $rows = dbFetchAll("SELECT * FROM `$table` LIMIT $chunkSize OFFSET $offset");
            if (!$rows) break;

            $cols = '`' . implode('`, `', array_keys($rows[0])) . '`';
            $valueGroups = [];
            foreach ($rows as $r) {
                $vals = array_map(function ($v) {
                    if ($v === null)    return 'NULL';
                    if (is_numeric($v)) return $v;
                    return "'" . addslashes((string)$v) . "'";
                }, array_values($r));
                $valueGroups[] = '(' . implode(', ', $vals) . ')';
            }
            foreach (array_chunk($valueGroups, 100) as $batch) {
                $out[] = "INSERT INTO `$table` ($cols) VALUES";
                $out[] = implode(",\n", $batch) . ';';
            }
            $offset += $chunkSize;
            if (count($rows) < $chunkSize) break;
        }
        $out[] = '';
    }

    $out[] = 'SET FOREIGN_KEY_CHECKS=1;';
    return implode("\n", $out);
}

// ── SQL statement splitter ────────────────────────────────────
// Character-level parser: tracks quoted strings so a semicolon
// inside a value or multiline CREATE TABLE body won't split early.
function splitSqlStatements(string $sql): array {
    $statements = [];
    $len        = strlen($sql);
    $i          = 0;
    $current    = '';
    $inSingle   = false;
    $inDouble   = false;

    while ($i < $len) {
        $ch   = $sql[$i];
        $next = $sql[$i + 1] ?? '';

        // line comment -- skip to EOL
        if (!$inSingle && !$inDouble && $ch === '-' && $next === '-') {
            while ($i < $len && $sql[$i] !== "\n") $i++;
            $i++;
            continue;
        }

        // single-quote toggle (handle escaped '' )
        if (!$inDouble && $ch === "'") {
            if ($inSingle && $next === "'") {
                $current .= "''";
                $i += 2;
                continue;
            }
            $inSingle = !$inSingle;
            $current .= $ch;
            $i++;
            continue;
        }

        // double-quote toggle
        if (!$inSingle && $ch === '"') {
            if ($inDouble && $next === '"') {
                $current .= '""';
                $i += 2;
                continue;
            }
            $inDouble = !$inDouble;
            $current .= $ch;
            $i++;
            continue;
        }

        // backslash escape inside quotes
        if (($inSingle || $inDouble) && $ch === '\\') {
            $current .= $ch . $next;
            $i += 2;
            continue;
        }

        // statement terminator (only outside quotes)
        if (!$inSingle && !$inDouble && $ch === ';') {
            $stmt = trim($current);
            if ($stmt !== '') {
                $statements[] = $stmt;
            }
            $current = '';
            $i++;
            continue;
        }

        $current .= $ch;
        $i++;
    }

    $stmt = trim($current);
    if ($stmt !== '') {
        $statements[] = $stmt;
    }

    return $statements;
}

// ── Download ─────────────────────────────────────────────────
if ($action === 'download_sql') {
    $slug     = preg_replace('/[^a-zA-Z0-9_-]/', '_', APP_NAME);
    $filename = 'backup_' . $slug . '_' . date('Y-m-d_His') . '.sql';

    logAction('EXPORT', 'backup', null, 'Admin downloaded SQL backup: ' . $filename);

    if (ob_get_level()) ob_end_clean();
    header('Content-Type: application/octet-stream');
    header('Content-Disposition: attachment; filename="' . $filename . '"');
    header('Cache-Control: no-cache, no-store, must-revalidate');
    header('Pragma: no-cache');
    header('Expires: 0');
    echo generateSqlDump();
    exit;
}

// ── Confirm token (AJAX) ─────────────────────────────────────
if ($action === 'confirm_restore') {
    $token = bin2hex(random_bytes(16));
    $_SESSION['restore_token'] = $token;
    header('Content-Type: application/json');
    echo json_encode(['token' => $token]);
    exit;
}

// ── Restore ──────────────────────────────────────────────────
if ($action === 'restore_db') {
    // CSRF-style token check
    if (
        empty($_POST['confirm_token']) ||
        $_POST['confirm_token'] !== ($_SESSION['restore_token'] ?? '')
    ) {
        flash('error', 'Invalid confirmation token. Please try again.');
        redirect('backup');
    }
    unset($_SESSION['restore_token']);

    if (empty($_FILES['sql_file']['tmp_name'])) {
        flash('error', 'No file uploaded.');
        redirect('backup');
    }

    $origName = $_FILES['sql_file']['name'] ?? '';
    if (strtolower(pathinfo($origName, PATHINFO_EXTENSION)) !== 'sql') {
        flash('error', 'Only .sql files are accepted.');
        redirect('backup');
    }

    $sql = file_get_contents($_FILES['sql_file']['tmp_name']);
    if (!$sql) {
        flash('error', 'Could not read the uploaded file.');
        redirect('backup');
    }

    // Split into individual statements (character-level parser handles
    // multi-line CREATE TABLE, semicolons inside quoted values, etc.)
    $statements = splitSqlStatements($sql);

    if (empty($statements)) {
        flash('error', 'No valid SQL statements found in the uploaded file.');
        redirect('backup');
    }

    $errors  = [];
    $count   = 0;

    // Force FK checks off for the whole restore session
    try { dbQuery('SET FOREIGN_KEY_CHECKS=0'); } catch (Throwable $e) {}
    try { dbQuery('SET SQL_MODE="NO_AUTO_VALUE_ON_ZERO"'); } catch (Throwable $e) {}

    foreach ($statements as $idx => $stmt) {
        $stmt = trim($stmt);
        if ($stmt === '') continue;

        // Skip SET statements we already ran or that PDO can't handle
        if (preg_match('/^SET\s+(FOREIGN_KEY_CHECKS|SQL_MODE|time_zone)/i', $stmt)) {
            continue;
        }

        try {
            dbQuery($stmt);
            $count++;
        } catch (Throwable $e) {
            $errors[] = [
                'n'    => $idx + 1,
                'sql'  => substr($stmt, 0, 120),
                'err'  => $e->getMessage(),
            ];
        }
    }

    try { dbQuery('SET FOREIGN_KEY_CHECKS=1'); } catch (Throwable $e) {}

    logAction(
        'IMPORT', 'backup', null,
        "Admin restored DB from: $origName ($count statements, " . count($errors) . " errors)"
    );

    if ($errors) {
        // Store errors in session so we can display them on the page
        $_SESSION['restore_errors'] = $errors;
        flash('warning', count($errors) . ' error(s) during restore. ' . $count . ' statements ran. See details below.');
    } else {
        flash('success', "Restore complete — $count statements executed successfully.");
    }
    redirect('backup');
}

// ── Page data ────────────────────────────────────────────────
$pageTitle  = 'Backup & Restore';
$sizeRow    = dbFetch("SELECT ROUND(SUM(data_length+index_length),0) AS size
                       FROM information_schema.tables WHERE table_schema=DATABASE()");
$dbSize     = $sizeRow ? (int)$sizeRow['size'] : 0;
$tableCount = count(dbFetchAll('SHOW TABLES'));

function formatBytes(int $bytes): string {
    if ($bytes >= 1048576) return round($bytes / 1048576, 2) . ' MB';
    if ($bytes >= 1024)    return round($bytes / 1024, 1)    . ' KB';
    return $bytes . ' B';
}

$logs = dbFetchAll(
    "SELECT * FROM action_logs WHERE module='backup' ORDER BY created_at DESC LIMIT 10"
) ?: [];

$restoreErrors = $_SESSION['restore_errors'] ?? [];
unset($_SESSION['restore_errors']);

require_once BASE_PATH . '/includes/header.php';
?>

<style>
.bk { max-width:680px }
.bk h1 { font-size:20px;font-weight:500;margin-bottom:1.5rem;display:flex;align-items:center;gap:10px }
.bk-card { background:var(--card-bg,#fff);border:0.5px solid var(--border-color,#e5e5e5);border-radius:10px;overflow:hidden;margin-bottom:1rem }
.bk-ch { display:flex;align-items:center;gap:8px;padding:12px 18px;border-bottom:0.5px solid var(--border-color,#e5e5e5);background:var(--surface-bg,#fafafa) }
.bk-ci { font-size:15px }
.bk-ct { font-size:12px;font-weight:600;color:var(--text-muted,#888);text-transform:uppercase;letter-spacing:.05em }
.bk-body { padding:18px }
.bk-stats { display:flex;gap:12px;margin-bottom:18px }
.bk-stat { flex:1;background:var(--surface-bg,#f5f5f5);border-radius:8px;padding:12px 14px }
.bk-sl { font-size:11px;color:var(--text-muted,#888);margin-bottom:4px;text-transform:uppercase;letter-spacing:.04em }
.bk-sv { font-size:20px;font-weight:500 }
.bk-sv.sm { font-size:13px;padding-top:4px }
.bk-btn { display:inline-flex;align-items:center;gap:7px;padding:9px 18px;font-size:13px;font-weight:500;border-radius:8px;border:0.5px solid var(--border-color,#e5e5e5);background:var(--card-bg,#fff);color:var(--text-primary,#111);cursor:pointer;font-family:inherit;text-decoration:none }
.bk-btn:hover { background:var(--surface-bg,#f5f5f5) }
.bk-btn.primary { background:var(--text-primary,#111);color:var(--card-bg,#fff);border-color:var(--text-primary,#111) }
.bk-btn.primary:hover { opacity:.85 }
.bk-btn.danger { background:#dc2626;color:#fff;border-color:#dc2626 }
.bk-btn.danger:hover { opacity:.85 }
.bk-btn:disabled, .bk-btn[disabled] { opacity:.4;cursor:not-allowed;pointer-events:none }
.bk-warn { background:#fff8e5;border:0.5px solid #ffe08a;border-radius:8px;padding:12px 14px;font-size:13px;color:#8a5d00;line-height:1.6;margin-bottom:14px }
.bk-upload { border:1.5px dashed var(--border-color,#ddd);border-radius:8px;padding:22px;text-align:center;cursor:pointer;transition:border-color .2s }
.bk-upload:hover,.bk-upload.over { border-color:var(--text-primary,#333) }
.bk-upload input[type=file] { display:none }
.bk-upl { font-size:13px;color:var(--text-muted,#888) }
.bk-upl strong { color:var(--text-primary,#111) }
.bk-ufile { display:none;margin-top:10px;font-size:13px;font-weight:500 }
.bk-row { display:flex;gap:10px;align-items:center;flex-wrap:wrap }
.bk-hint { font-size:12px;color:var(--text-muted,#888) }
.bk-div { border:none;border-top:0.5px solid var(--border-color,#eee);margin:16px 0 }
/* log table */
.bk-tbl { width:100%;font-size:12px;border-collapse:collapse }
.bk-tbl th { text-align:left;padding:6px 10px;color:var(--text-muted,#888);font-weight:500;border-bottom:0.5px solid var(--border-color,#eee) }
.bk-tbl td { padding:7px 10px;border-bottom:0.5px solid var(--border-color,#f0f0f0);vertical-align:top }
.bk-tbl tr:last-child td { border-bottom:none }
.bk-badge { display:inline-block;font-size:11px;padding:2px 8px;border-radius:20px }
.bk-badge.ex { background:#e8f4fd;color:#1565c0 }
.bk-badge.im { background:#fff3cd;color:#856404 }
/* error detail panel */
.bk-errs { background:#fef2f2;border:0.5px solid #fca5a5;border-radius:8px;overflow:hidden;margin-bottom:1rem }
.bk-errs-head { padding:10px 14px;background:#fee2e2;font-size:12px;font-weight:600;color:#991b1b }
.bk-err-row { padding:8px 14px;border-top:0.5px solid #fca5a5;font-size:12px }
.bk-err-n { color:#991b1b;font-weight:600;margin-right:6px }
.bk-err-sql { font-family:var(--font-mono,monospace);background:#fff5f5;padding:2px 6px;border-radius:4px;color:#7f1d1d;word-break:break-all }
.bk-err-msg { color:#b91c1c;margin-top:3px }
.bk-backdrop { display:none;position:fixed;inset:0;background:rgba(0,0,0,.5);z-index:999;align-items:center;justify-content:center }
.bk-backdrop.open { display:flex }
.bk-modal { background:var(--card-bg,#fff);border-radius:12px;padding:28px;max-width:420px;width:90%;border:0.5px solid var(--border-color,#ddd) }
.bk-modal h2 { font-size:16px;font-weight:500;margin-bottom:10px }
.bk-modal p { font-size:13px;color:var(--text-muted,#666);line-height:1.6;margin-bottom:16px }
.bk-cinput { width:100%;font-size:13px;padding:8px 10px;border:0.5px solid var(--border-color,#ddd);border-radius:8px;background:var(--card-bg,#fff);color:var(--text-primary,#111);margin-bottom:14px;font-family:inherit }
.bk-cinput:focus { outline:none;border-color:var(--text-primary,#333) }
.bk-mfoot { display:flex;gap:10px;justify-content:flex-end }
code.inline { background:var(--surface-bg,#f5f5f5);padding:1px 6px;border-radius:4px;font-family:var(--font-mono,monospace) }
</style>

<div class="bk">
  <h1>🗄️ Backup &amp; Restore</h1>

  <!-- Download card -->
  <div class="bk-card">
    <div class="bk-ch"><span class="bk-ci">⬇️</span><span class="bk-ct">Download Backup</span></div>
    <div class="bk-body">
      <div class="bk-stats">
        <div class="bk-stat">
          <div class="bk-sl">DB Size</div>
          <div class="bk-sv"><?= formatBytes($dbSize) ?></div>
        </div>
        <div class="bk-stat">
          <div class="bk-sl">Tables</div>
          <div class="bk-sv"><?= $tableCount ?></div>
        </div>
        <div class="bk-stat">
          <div class="bk-sl">Generated</div>
          <div class="bk-sv sm"><?= date('d M Y, H:i') ?></div>
        </div>
      </div>
      <form method="POST">
        <input type="hidden" name="action" value="download_sql">
        <div class="bk-row">
          <button type="submit" class="bk-btn primary">⬇️ Download .sql backup</button>
          <span class="bk-hint">Pure-PHP dump — no mysqldump required.</span>
        </div>
      </form>
    </div>
  </div>

  <!-- Restore card -->
  <div class="bk-card">
    <div class="bk-ch"><span class="bk-ci">⬆️</span><span class="bk-ct">Restore from Backup</span></div>
    <div class="bk-body">
      <div class="bk-warn">
        ⚠️ <strong>Warning:</strong> Restoring will drop and recreate all tables.
        This is irreversible. Download a fresh backup first before proceeding.
      </div>

      <div class="bk-upload" id="uploadArea" onclick="document.getElementById('sqlFile').click()">
        <input type="file" id="sqlFile" accept=".sql" onchange="onFileSelected(this)">
        <div class="bk-upl">
          <span style="font-size:24px;display:block;margin-bottom:8px">📂</span>
          <strong>Click to select</strong> or drag &amp; drop a .sql file
        </div>
        <div class="bk-ufile" id="selectedFile"></div>
      </div>

      <hr class="bk-div">

      <div class="bk-row">
        <button type="button" class="bk-btn danger" id="restoreBtn" disabled onclick="openModal()">
          🔄 Restore Database
        </button>
        <span class="bk-hint" id="restoreHint">Select a .sql file to enable restore.</span>
      </div>
    </div>
  </div>

  <!-- Activity log -->
  <?php if ($logs): ?>
  <div class="bk-card">
    <div class="bk-ch"><span class="bk-ci">📋</span><span class="bk-ct">Backup Activity</span></div>
    <div class="bk-body" style="padding:0">
      <table class="bk-tbl">
        <thead>
          <tr><th>Action</th><th>Details</th><th>Date</th></tr>
        </thead>
        <tbody>
          <?php foreach ($logs as $log): ?>
          <tr>
            <td>
              <span class="bk-badge <?= $log['action'] === 'EXPORT' ? 'ex' : 'im' ?>">
                <?= e($log['action']) ?>
              </span>
            </td>
            <td style="color:var(--text-muted,#888)"><?= e($log['note'] ?? '—') ?></td>
            <td style="white-space:nowrap;color:var(--text-muted,#888)">
              <?= e(date('d M Y H:i', strtotime($log['created_at']))) ?>
            </td>
          </tr>
          <?php endforeach ?>
        </tbody>
      </table>
    </div>
  </div>
  <?php endif ?>

  <!-- Restore error details (shown after a failed restore) -->
  <?php if ($restoreErrors): ?>
  <div class="bk-errs">
    <div class="bk-errs-head">❌ <?= count($restoreErrors) ?> statement(s) failed during restore</div>
    <?php foreach ($restoreErrors as $e): ?>
    <div class="bk-err-row">
      <span class="bk-err-n">#<?= $e['n'] ?></span>
      <div class="bk-err-sql"><?= htmlspecialchars($e['sql']) ?>…</div>
      <div class="bk-err-msg"><?= htmlspecialchars($e['err']) ?></div>
    </div>
    <?php endforeach ?>
  </div>
  <?php endif ?>

</div>

<!-- Restore confirmation modal -->
<div class="bk-backdrop" id="modal">
  <div class="bk-modal">
    <h2>⚠️ Confirm Restore</h2>
    <p>
      You are about to <strong>overwrite the entire database</strong> with<br>
      <strong id="modalFile" style="word-break:break-all">—</strong>.<br><br>
      Type <code class="inline">RESTORE</code> to confirm. This cannot be undone.
    </p>
    <input type="text" class="bk-cinput" id="confirmInput"
           placeholder="Type RESTORE to confirm" oninput="checkConfirm(this)" autocomplete="off">
    <form method="POST" enctype="multipart/form-data" id="restoreForm">
      <input type="hidden" name="action" value="restore_db">
      <input type="hidden" name="confirm_token" id="confirmToken">
      <input type="file"   name="sql_file" id="hiddenFile" style="display:none" accept=".sql">
      <div class="bk-mfoot">
        <button type="button" class="bk-btn" onclick="closeModal()">Cancel</button>
        <button type="submit" class="bk-btn danger" id="doRestore" disabled>🔄 Yes, Restore</button>
      </div>
    </form>
  </div>
</div>

<script>
let pickedFile = null;

function onFileSelected(input) {
  pickedFile = input.files[0] || null;
  const sf  = document.getElementById('selectedFile');
  const btn = document.getElementById('restoreBtn');
  const hint = document.getElementById('restoreHint');
  if (pickedFile) {
    sf.textContent = '✅ ' + pickedFile.name + ' (' + fmtSize(pickedFile.size) + ')';
    sf.style.display = 'block';
    btn.disabled = false;
    hint.textContent = 'Ready — click Restore to proceed.';
  } else {
    sf.style.display = 'none';
    btn.disabled = true;
    hint.textContent = 'Select a .sql file to enable restore.';
  }
}

function fmtSize(b) {
  if (b >= 1048576) return (b/1048576).toFixed(2) + ' MB';
  if (b >= 1024)    return (b/1024).toFixed(1) + ' KB';
  return b + ' B';
}

// Drag & drop
const area = document.getElementById('uploadArea');
area.addEventListener('dragover', e => { e.preventDefault(); area.classList.add('over'); });
area.addEventListener('dragleave', () => area.classList.remove('over'));
area.addEventListener('drop', e => {
  e.preventDefault(); area.classList.remove('over');
  const f = e.dataTransfer.files[0];
  if (f && f.name.endsWith('.sql')) {
    const dt = new DataTransfer(); dt.items.add(f);
    document.getElementById('sqlFile').files = dt.files;
    onFileSelected(document.getElementById('sqlFile'));
  }
});

async function openModal() {
  if (!pickedFile) return;
  document.getElementById('modalFile').textContent = pickedFile.name;
  document.getElementById('confirmInput').value    = '';
  document.getElementById('doRestore').disabled    = true;

  // Get one-time server token
  const res  = await fetch('?module=backup&action=confirm_restore', { method: 'POST' });
  const data = await res.json();
  document.getElementById('confirmToken').value = data.token;

  // Copy file to hidden input inside the real form
  const dt = new DataTransfer(); dt.items.add(pickedFile);
  document.getElementById('hiddenFile').files = dt.files;

  document.getElementById('modal').classList.add('open');
}

function closeModal() {
  document.getElementById('modal').classList.remove('open');
}

function checkConfirm(input) {
  document.getElementById('doRestore').disabled = (input.value.trim() !== 'RESTORE');
}

document.getElementById('modal').addEventListener('click', e => {
  if (e.target === document.getElementById('modal')) closeModal();
});
</script>

<?php require_once BASE_PATH . '/includes/footer.php'; ?>