<?php
// BanglaEdu CMS Configuration - Auto-generated by Setup
define('DB_HOST', 'localhost');
define('DB_NAME', 'sc');
define('DB_USER', 'root');
define('DB_PASS', '');
define('DB_CHARSET', 'utf8mb4');
define('SITE_URL', (isset($_SERVER['HTTPS']) && $_SERVER['HTTPS']==='on' ? 'https' : 'http') . '://' . ($_SERVER['HTTP_HOST'] ?? 'localhost'));
define('APP_VERSION', '1.0.0');
define('UPLOAD_MAX_SIZE', 10 * 1024 * 1024); // 10MB
